
-- First, let's see what products we currently have
SELECT name, slug FROM public.products ORDER BY name;

-- Create the new Dakkapel product (this should work fine)
INSERT INTO public.products (
  id,
  name,
  slug,
  description,
  seo_title,
  seo_description,
  seo_canonical_url,
  hero_badge,
  hero_title,
  hero_description,
  hero_background_image,
  hero_primary_button_text,
  hero_primary_button_link,
  hero_secondary_button_text,
  hero_secondary_button_link,
  hero_guarantees,
  benefits,
  introduction_title,
  introduction_content,
  introduction_quick_links,
  introduction_cta_text,
  introduction_cta_link,
  what_are_title,
  what_are_content,
  features,
  benefits_title,
  benefits_description,
  benefits_main_content,
  benefits_stats,
  benefits_cta_text,
  benefits_cta_link,
  options_title,
  options_description,
  options_categories,
  services_title,
  services_description,
  services_items,
  information_title,
  information_image,
  information_image_alt,
  information_tabs,
  information_did_you_know,
  faq_title,
  faq_description,
  faq,
  show_regions,
  is_active,
  sort_order,
  template_type
) VALUES (
  gen_random_uuid(),
  'Dakkapel',
  'dakkapel',
  'Professionele dakkapel plaatsing en renovatie voor meer ruimte en licht in uw woning.',
  'Dakkapel Plaatsing & Renovatie | Duurzaam Wonen Nederland',
  'Vakkundige dakkapel plaatsing en renovatie. Meer ruimte, licht en waarde voor uw woning. ✓ Ervaren specialisten ✓ Vakkundige montage ✓ 15 jaar garantie',
  'https://duurzaamwonen.info/dakkapel',
  'Dakkapel Specialist',
  'Professionele dakkapel plaatsing',
  'Meer ruimte, licht en waarde voor uw woning met een vakkundig geplaatste dakkapel.',
  '/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png',
  'Offerte aanvragen',
  '/offerte',
  'Meer informatie',
  NULL,
  '["15 jaar productgarantie", "Gratis advies", "Vakkundige montage"]'::json,
  '["Meer woonruimte - Extra vierkante meters", "Meer daglicht - Natuurlijk licht in huis", "Hogere woningwaarde - Investering die zich terugbetaalt"]'::json,
  'Waarom kiezen voor een dakkapel?',
  '["Een dakkapel is een uitstekende manier om extra woonruimte te creëren en meer natuurlijk licht in uw woning te krijgen. Bij Duurzaam Wonen Nederland helpen we u van ontwerp tot realisatie.", "Met onze jarenlange ervaring in dakkapel plaatsing zorgen we voor een vakkundige uitvoering die voldoet aan alle bouwvoorschriften en uw verwachtingen overtreft."]'::json,
  '[{"href": "#wat-zijn", "text": "Wat is een dakkapel?"}, {"href": "#voordelen", "text": "Voordelen dakkapel"}, {"href": "#types", "text": "Dakkapel types"}, {"href": "#kosten", "text": "Dakkapel kosten"}]'::json,
  'Vraag nu vrijblijvend een offerte aan',
  '/offerte',
  'Wat is een dakkapel?',
  '["Een dakkapel is een verticale uitbouw in het dakvlak die extra ruimte en licht creëert op de zolderverdieping. Het is een populaire manier om de woonoppervlakte van uw huis uit te breiden zonder uitbouw aan de voet van het huis.", "Dakkapellen worden in verschillende vormen en stijlen uitgevoerd, van traditionele puntkappen tot moderne platte dakkapellen, elk met hun eigen karakteristieke uitstraling en voordelen."]'::json,
  '["Meer woonruimte", "Extra daglicht", "Betere ventilatie", "Hogere woningwaarde", "Verschillende stijlen beschikbaar", "Vakkundige plaatsing"]'::json,
  'Voordelen van een dakkapel',
  'Een dakkapel biedt tal van voordelen voor uw woning en wooncomfort.',
  '["Extra woonruimte: Een dakkapel vergroot de nuttige oppervlakte van uw zolderverdieping aanzienlijk, waardoor u meer leefruimte krijgt.", "Meer natuurlijk licht: Door de verticale ramen krijgt u veel meer daglicht binnen dan met dakramen alleen.", "Betere ventilatie: Dakkapelramen kunnen worden geopend voor optimale ventilatie van de zolderruimte.", "Verhoogde woningwaarde: Een professioneel geplaatste dakkapel verhoogt de waarde van uw woning.", "Architectonische uitstraling: Een dakkapel geeft uw woning een karakteristieke en aantrekkelijke uitstraling."]'::json,
  '[{"value": "25m²", "label": "Gemiddelde ruimtewinst"}, {"value": "15-20%", "label": "Waardestijging woning"}, {"value": "300%", "label": "Meer daglicht"}]'::json,
  'Vraag vrijblijvend een offerte aan!',
  '/offerte',
  'Dakkapel types en opties',
  'Verschillende dakkapel types voor elke situatie en stijl.',
  '[{"title": "Puntkap dakkapel", "items": ["Traditionele uitstraling", "Geschikt voor klassieke woningen", "Driehoekige vorm", "Pannen afwerking"]}, {"title": "Platte dakkapel", "items": ["Moderne uitstraling", "Maximale ruimtewinst", "Strakke lijnen", "EPDM of zink afwerking"]}, {"title": "Lessenaarskap", "items": ["Schuine achterwand", "Goede prijs-kwaliteit verhouding", "Veel daglicht", "Verschillende afwerkingen"]}, {"title": "Ronde dakkapel", "items": ["Unieke vormgeving", "Zachte rondingen", "Karakteristieke uitstraling", "Op maat gemaakt"]}, {"title": "Gevel dakkapel", "items": ["Doorlopend tot de gevel", "Maximale ruimtebenutting", "Moderne uitstraling", "Optimale lichtinval"]}]'::json,
  'Onze dakkapel diensten',
  'Van ontwerp tot oplevering, wij verzorgen het complete proces.',
  '[{"title": "Ontwerp & advies", "description": "Professioneel ontwerp op maat voor uw situatie", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["3D visualisatie", "Bouwvergunning aanvraag", "Constructieberekening", "Stijladvies"], "linkText": "Meer over ontwerp", "linkUrl": "/dakkapel/ontwerp"}, {"title": "Dakkapel plaatsing", "description": "Vakkundige plaatsing door ervaren specialisten", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Ervaren monteurs", "Kwaliteitsmaterialen", "Waterafvoer systeem", "15 jaar garantie"], "linkText": "Meer over plaatsing", "linkUrl": "/dakkapel/plaatsing"}, {"title": "Renovatie & onderhoud", "description": "Onderhoud en renovatie van bestaande dakkapellen", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Dakbedekking vernieuwen", "Ramen vervangen", "Isolatie verbeteren", "Afvoer onderhoud"], "linkText": "Meer over renovatie", "linkUrl": "/dakkapel/renovatie"}]'::json,
  'Praktische informatie',
  '/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png',
  'Dakkapel informatie',
  '[{"title": "Bouwvergunning", "content": "Voor de meeste dakkapellen is een bouwvergunning vereist. Wij verzorgen de complete aanvraag voor u, inclusief tekeningen en berekeningen. De vergunningsprocedure duurt gemiddeld 6-8 weken."}, {"title": "Constructie", "content": "Elke dakkapel wordt voorzien van een solide constructie die voldoet aan alle bouwvoorschriften. We voeren altijd een constructieberekening uit om de veiligheid te garanderen."}, {"title": "Isolatie", "content": "Moderne dakkapellen worden volledig geïsoleerd volgens de nieuwste normen. Dit zorgt voor optimaal wooncomfort en energiebesparing."}, {"title": "Afwerking", "content": "De afwerking van uw dakkapel wordt volledig afgestemd op uw woning. Van traditionele pannen tot moderne zink of EPDM dakbedekking."}]'::json,
  '[{"title": "Wist u dat?", "content": "Een dakkapel kan tot 25 vierkante meter extra woonruimte opleveren en de waarde van uw woning met 15-20% verhogen. Bovendien krijgt u tot 300% meer daglicht binnen dan met alleen dakramen."}]'::json,
  'Veelgestelde vragen',
  'Antwoorden op de meest gestelde vragen over dakkapellen.',
  '[{"question": "Heb ik een bouwvergunning nodig voor een dakkapel?", "answer": "Ja, voor de meeste dakkapellen is een bouwvergunning vereist. Wij verzorgen de complete aanvraag inclusief tekeningen en berekeningen."}, {"question": "Hoeveel kost een dakkapel?", "answer": "De kosten voor een dakkapel variëren tussen €15.000 en €35.000,afhankelijk van grootte, type en afwerking. Vraag een vrijblijvende offerte aan voor een exacte prijsopgave."}, {"question": "Hoe lang duurt de plaatsing van een dakkapel?", "answer": "De plaatsing van een dakkapel duurt gemiddeld 2-3 werkdagen, afhankelijk van de complexiteit en weersomstandigheden."}, {"question": "Welk type dakkapel past bij mijn woning?", "answer": "Het type dakkapel hangt af van de architectuur van uw woning en uw persoonlijke voorkeur. Onze adviseurs helpen u graag bij het maken van de juiste keuze."}, {"question": "Krijg ik garantie op de dakkapel?", "answer": "Ja, wij geven 15 jaar productgarantie op de dakkapel en 10 jaar servicegarantie op de montage."}]'::json,
  true,
  true,
  5,
  'service_page'
);

-- Update Kunststof Schuifpuien content (keep the same slug)
UPDATE public.products 
SET 
  hero_title = 'Kunststof schuifpuien op maat',
  hero_description = 'Creëer een naadloze overgang tussen binnen en buiten met onze hoogwaardige kunststof schuifpuien.',
  introduction_title = 'Waarom kiezen voor kunststof schuifpuien?',
  introduction_content = '["Kunststof schuifpuien zijn de perfecte oplossing voor wie houdt van veel licht en een open gevoel in huis. Met grote glaspanelen creëert u een naadloze verbinding tussen uw interieur en tuin.", "Onze schuifpuien combineren moderne technologie met tijdloos design, waardoor u jarenlang kunt genieten van comfort, veiligheid en energiebesparing."]'::json,
  what_are_title = 'Wat zijn kunststof schuifpuien?',
  what_are_content = '["Kunststof schuifpuien zijn grote glaspartijen die bestaan uit meerdere panelen die horizontaal langs elkaar schuiven. Ze worden vaak gebruikt als terrasdeuren en bieden een spectaculair uitzicht naar buiten.", "Door de grote glasoppervlakken en slanke profielen krijgt u maximaal licht binnen en een gevoel van ruimte. De schuiffunctie maakt het mogelijk om grote openingen te creëren zonder dat deuren naar binnen of buiten openslaan."]'::json,
  benefits_title = 'Voordelen van kunststof schuifpuien',
  benefits_description = 'Ontdek waarom kunststof schuifpuien de perfecte keuze zijn voor uw woning.',
  benefits_main_content = '["Maximaal licht: Door de grote glasoppervlakken krijgt u veel natuurlijk licht binnen, waardoor uw woonruimte groter en vriendelijker aanvoelt.", "Ruimtebesparend: Schuifpuien nemen geen zwenkruimte in beslag, waardoor u optimaal gebruik kunt maken van uw leefruimte.", "Uitstekende isolatie: Moderne schuifpuien zijn voorzien van hoogwaardige isolatie en HR+++ beglazing voor optimaal wooncomfort.", "Veiligheid: Standaard voorzien van meerpuntssluitingen en veiligheidsglas voor maximale beveiliging.", "Onderhoudsarm: Kunststof profielen behouden jarenlang hun uitstraling zonder schilderen of behandelen."]'::json,
  options_title = 'Schuifpui configuraties',
  options_description = 'Verschillende opstellingen voor elke situatie.',
  options_categories = '[{"title": "2-delig systeem", "items": ["1 vast paneel + 1 schuifpaneel", "Geschikt voor kleinere openingen", "Economische oplossing", "Minimale onderhoudskosten"]}, {"title": "3-delig systeem", "items": ["2 schuifpanelen + 1 vast paneel", "Standaard configuratie", "Goede prijs-kwaliteit verhouding", "Veel variatiemogelijkheden"]}, {"title": "4-delig systeem", "items": ["Meerdere schuifpanelen mogelijk", "Maximale opening mogelijk", "Luxe uitstraling", "Op maat gemaakt"]}, {"title": "Lift & Slide", "items": ["Premium schuifsysteem", "Zeer soepel schuiven", "Extra grote panelen mogelijk", "Topkwaliteit hardware"]}]'::json,
  services_items = '[{"title": "Maatwerk schuifpuien", "description": "Elke schuifpui wordt op maat gemaakt voor uw specifieke situatie", "image": "/lovable-uploads/c5500638-e554-4499-8490-7c52a4ec2a55.png", "features": ["Op maat gemaakt", "Verschillende kleuren", "Diverse glasopties", "Professionele montage"], "linkText": "Meer over maatwerk", "linkUrl": "/schuifpuien/maatwerk"}, {"title": "Schuifpui renovatie", "description": "Vervanging van oude schuifpuien voor beter comfort en uitstraling", "image": "/lovable-uploads/c5500638-e554-4499-8490-7c52a4ec2a55.png", "features": ["Demontage oude pui", "Nieuwe kozijnen", "Professionele afwerking", "Minimale overlast"], "linkText": "Meer over renovatie", "linkUrl": "/schuifpuien/renovatie"}]'::json,
  information_tabs = '[{"title": "Profielen", "content": "Onze schuifpuien worden uitgevoerd in hoogwaardige kunststof profielen met meerkamer systeem voor optimale isolatie. Verkrijgbaar in wit en verschillende houtdecors."}, {"title": "Beglazing", "content": "Standaard voorzien van HR+++ beglazing (triple glas) voor maximale isolatie. Ook verkrijgbaar met zonwering glas, veiligheidsglas of gelaagd glas voor extra veiligheid."}, {"title": "Hardware", "content": "Hoogwaardige schuifhardware van topmerken zoals Siegenia en Roto. Verkrijgbaar in verschillende kleuren en uitvoeringen, van standaard tot lift & slide systemen."}, {"title": "Onderhoud", "content": "Kunststof schuifpuien zijn zeer onderhoudsarm. Regelmatige reiniging van glas en profielen en smering van de hardware is voldoende om jarenlang soepel te blijven functioneren."}]'::json,
  faq = '[{"question": "Wat is het voordeel van een schuifpui ten opzichte van openslaande deuren?", "answer": "Schuifpuien nemen geen zwenkruimte in beslag en kunnen veel bredere openingen creëren. Ook krijgt u meer glas en daarmee meer licht binnen."}, {"question": "Kunnen schuifpuien goed worden afgesloten?", "answer": "Ja, moderne schuifpuien zijn voorzien van meerpuntssluitingen die net zo veilig zijn als normale deuren. Ook zijn ze verkrijgbaar met RC2 inbraakwerend glas."}, {"question": "Hoeveel onderhoud heeft een kunststof schuifpui nodig?", "answer": "Zeer weinig. Regelmatige reiniging en af en toe de hardware smeren is voldoende. De kunststof profielen hoeven nooit geschilderd te worden."}, {"question": "Wat zijn de kosten voor een kunststof schuifpui?", "answer": "De kosten variëren tussen €2.500 en €6.000 afhankelijk van afmetingen, configuratie en opties. Vraag een vrijblijvende offerte aan voor een exacte prijsopgave."}]'::json
WHERE slug = 'kunststof-schuifpuien';

-- Update the product that has slug 'kunststof-deuren' to become proper Kunststof Deuren content
UPDATE public.products 
SET 
  name = 'Kunststof Deuren',
  description = 'Hoogwaardige kunststof deuren voor optimale veiligheid, isolatie en uitstraling van uw woning.',
  seo_title = 'Kunststof Deuren | Veilig & Energiezuinig | Duurzaam Wonen Nederland',
  seo_description = 'Kunststof deuren van topkwaliteit. ✓ Uitstekende isolatie ✓ Inbraakwerend ✓ Onderhoudsvrij ✓ Vele stijlen ✓ 15 jaar garantie. Vraag vrijblijvend offerte aan!',
  seo_canonical_url = 'https://duurzaamwonen.info/kunststof-deuren',
  hero_badge = 'Deur Specialist',
  hero_title = 'Kunststof deuren van topkwaliteit',
  hero_description = 'Veilige, energiezuinige en onderhoudsvrije kunststof deuren die perfect passen bij uw woning.',
  introduction_title = 'Waarom kiezen voor kunststof deuren?',
  introduction_content = '["Kunststof deuren combineren uitstekende isolatie, hoge veiligheid en duurzaamheid in één product. Ze zijn de perfecte keuze voor wie comfort, veiligheid en onderhoudsgemak belangrijk vindt.", "Met onze ruime keuze aan stijlen, kleuren en beglazing vindt u altijd een deur die perfect past bij de architectuur van uw woning."]'::json,
  what_are_title = 'Wat zijn kunststof deuren?',
  what_are_content = '["Kunststof deuren zijn voordelen gemaakt van hoogwaardig PVC-profiel met meerkamer systeem. Ze bieden uitstekende isolatie, zijn volledig onderhoudsvrij en verkrijgbaar in talloze uitvoeringen.", "Door hun constructie zijn ze uiterst duurzaam en behouden ze jarenlang hun mooie uitstraling zonder dat u ze hoeft te schilderen of anderszins te behandelen."]'::json,
  benefits_title = 'Voordelen van kunststof deuren',
  benefits_description = 'Ontdek waarom kunststof deuren de slimme keuze zijn voor uw woning.',
  benefits_main_content = '["Uitstekende isolatie: Door het meerkamer systeem en de goede afdichting blijft warmte binnen en kou buiten, wat resulteert in lagere energiekosten.", "Hoge veiligheid: Standaard voorzien van meerpuntssluitingen en verkrijgbaar met inbraakwerende beglazing en hardware voor optimale beveiliging.", "Onderhoudsvrij: Kunststof deuren behouden jarenlang hun uitstraling zonder schilderen. Alleen af en toe schoonmaken is voldoende.", "Duurzaam: Een kunststof deur gaat gemakkelijk 30-40 jaar mee en is aan het einde van de levensduur volledig recyclebaar.", "Veel keuzemogelijkheden: Verkrijgbaar in vele kleuren, glaspaneel opties en deurstijlen om perfect aan te sluiten bij uw woonstijl."]'::json,
  options_title = 'Deur types en stijlen',
  options_description = 'Van klassiek tot modern, wij hebben de perfecte deur voor uw woning.',
  options_categories = '[{"title": "Voordeur", "items": ["Representatieve uitstraling", "Meerpuntssluitingen", "Inbraakwerende opties", "Diverse glaspanelen"]}, {"title": "Achterdeur", "items": ["Praktische indeling", "Grote glaspartijen mogelijk", "Verschillende openingen", "Optimaal daglicht"]}, {"title": "Tuindeur", "items": ["Openslaand of schuivend", "Lage drempel mogelijk", "Uitzicht op tuin", "Veilige afsluitingen"]}, {"title": "Binnendeur", "items": ["Diverse uitvoeringen", "Geluidsisolatie", "Brandwerende opties", "Stijlvolle afwerking"]}]'::json,
  services_items = '[{"title": "Nieuwe kunststof deuren", "description": "Complete levering en montage van nieuwe kunststof deuren", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Maatwerk mogelijk", "Professionele montage", "Diverse stijlen", "15 jaar garantie"], "linkText": "Meer over nieuwe deuren", "linkUrl": "/kunststof-deuren/nieuw"}, {"title": "Deur renovatie", "description": "Vervanging van oude deuren voor beter comfort en veiligheid", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Demontage oude deur", "Kozijn aanpassingen", "Perfecte pasvorm", "Minimale overlast"], "linkText": "Meer over renovatie", "linkUrl": "/kunststof-deuren/renovatie"}]'::json,
  information_tabs = '[{"title": "Veiligheid", "content": "Onze kunststof deuren zijn standaard voorzien van meerpuntssluitingen en kunnen worden uitgerust met inbraakwerende beglazing en hang- en sluitwerk volgens RC2 of RC3 normen."}, {"title": "Isolatie", "content": "Het meerkamer profiel systeem in combinatie met hoogwaardige afdichtingen zorgt voor uitstekende thermische isolatie. Dit resulteert in lager energieverbruik en hoger wooncomfort."}, {"title": "Beglazing", "content": "Verkrijgbaar met diverse beglazingsopties: van decoratief glas tot veiligheidsglas en van gelaagd glas tot HR+++ isolatieglas voor optimale prestaties."}, {"title": "Onderhoud", "content": "Kunststof deuren zijn praktisch onderhoudsvrij. Regelmatige reiniging met water en een mild schoonmaakmiddel is voldoende om ze er jarenlang als nieuw uit te laten zien."}]'::json,
  faq = '[{"question": "Hoe veilig zijn kunststof deuren?", "answer": "Zeer veilig. Standaard voorzien van meerpuntssluitingen en verkrijgbaar met inbraakwerende beglazing en hardware. Ze kunnen voldoen aan RC2 en RC3 inbraaknormen."}, {"question": "Gaan kunststof deuren lang mee?", "answer": "Ja, een kwaliteitsvolle kunststof deur gaat gemakkelijk 30-40 jaar mee zonder dat de uitstraling achteruitgaat of onderhoud nodig is."}, {"question": "Welke kleuren zijn beschikbaar?", "answer": "Wij leveren kunststof deuren in wit, diverse RAL kleuren en verschillende houtdecors. Ook tweekleurige uitvoeringen zijn mogelijk."}, {"question": "Wat kosten kunststof deuren?", "answer": "De prijs varieert tussen €800 en €2.500 afhankelijk van afmetingen, uitvoering en opties. Vraag een vrijblijvende offerte aan voor een exacte prijsopgave."}]'::json
WHERE slug = 'kunststof-deuren';

-- Update Gevelbekleding
UPDATE public.products 
SET 
  hero_title = 'Moderne gevelbekleding voor uw woning',
  hero_description = 'Verbeter de uitstraling, isolatie en waarde van uw woning met onze hoogwaardige gevelbekleding.',
  introduction_title = 'Waarom kiezen voor nieuwe gevelbekleding?',
  introduction_content = '["Gevelbekleding is een uitstekende manier om uw woning een moderne uitstraling te geven, de isolatiewaarde te verbeteren en tegelijkertijd onderhoudskosten te besparen.", "Of u nu kiest voor kunststof, hout of composiet gevelbekleding, wij zorgen voor een professionele montage die jarenlang meegaat en uw woning een frisse nieuwe look geeft."]'::json,
  what_are_title = 'Wat is gevelbekleding?',
  what_are_content = '["Gevelbekleding is het buitenmateriaal waarmee de gevel van uw woning wordt afgewerkt. Het beschermt de onderliggende constructie tegen weersinvloeden en bepaalt in grote mate de uitstraling van uw huis.", "Moderne gevelbekleding wordt vaak gecombineerd met extra isolatie, waardoor u niet alleen uw woning opknapt maar ook het wooncomfort verbetert en energiekosten bespaart."]'::json,
  benefits_title = 'Voordelen van nieuwe gevelbekleding',
  benefits_description = 'Ontdek de vele voordelen die gevelbekleding biedt voor uw woning.',
  benefits_main_content = '["Verbeterde isolatie: Door gevelbekleding te combineren met isolatiemateriaal verbetert u de energieprestatie van uw woning aanzienlijk.", "Moderne uitstraling: Geef uw woning een frisse, moderne look die de uitstraling en waarde van uw eigendom verhoogt.", "Onderhoudsarm: Vooral kunststof en composiet gevelbekleding vereist minimaal onderhoud en behoudt jarenlang de mooie uitstraling.", "Weerbescherming: Goede gevelbekleding beschermt uw woning tegen regen, wind, vorst en UV-straling.", "Geluidsisolatie: Extra isolatie achter de gevelbekleding zorgt ook voor betere geluidsisolatie van buitengeluiden."]'::json,
  options_title = 'Gevelbekleding materialen',
  options_description = 'Verschillende materialen voor elke smaak en budget.',
  options_categories = '[{"title": "Kunststof gevelbekleding", "items": ["64 verschillende kleuren", "Volledig onderhoudsvrij", "Lange levensduur", "Goede prijs-kwaliteit verhouding"]}, {"title": "Houten gevelbekleding", "items": ["Natuurlijke uitstraling", "Duurzaam FSC hout", "Diverse houtsoorten", "Klassieke uitstraling"]}, {"title": "Composiet gevelbekleding", "items": ["Houtlook zonder onderhoud", "Zeer duurzaam", "Kleurfast", "Premium kwaliteit"]}, {"title": "Fiber cement", "items": ["Robuust en duurzaam", "Brandveilig", "Verschillende structuren", "Professionele uitstraling"]}]'::json,
  services_items = '[{"title": "Gevelbekleding montage", "description": "Complete montage van nieuwe gevelbekleding inclusief isolatie", "image": "/lovable-uploads/c5500638-e554-4499-8490-7c52a4ec2a55.png", "features": ["Isolatie mogelijk", "Professionele montage", "Diverse materialen", "Lange garantie"], "linkText": "Meer over montage", "linkUrl": "/gevelbekleding/montage"}, {"title": "Gevel renovatie", "description": "Complete renovatie van oude gevels voor moderne uitstraling", "image": "/lovable-uploads/c5500638-e554-4499-8490-7c52a4ec2a55.png", "features": ["Demontage oude bekleding", "Isolatie verbetering", "Nieuwe bekleding", "Turn-key oplossing"], "linkText": "Meer over renovatie", "linkUrl": "/gevelbekleding/renovatie"}]'::json,
  information_tabs = '[{"title": "Materialen", "content": "Wij werken met verschillende gevelbekleding materialen: kunststof (64 kleuren), natuurlijk hout (diverse houtsoorten), composiet (houtlook zonder onderhoud) en fiber cement (robuust en brandveilig)."}, {"title": "Isolatie", "content": "Gevelbekleding wordt vaak gecombineerd met isolatie. Wij kunnen uw gevel isoleren met glaswol, steenwol of PIR-isolatie voor optimale energieprestaties."}, {"title": "Montage", "content": "Professionele montage is cruciaal voor een mooi en duurzaam resultaat. Onze monteurs hebben jarenlange ervaring en werken volgens de nieuwste normen en richtlijnen."}, {"title": "Onderhoud", "content": "Het onderhoudsschema hangt af van het gekozen materiaal. Kunststof en composiet zijn vrijwel onderhoudsvrij, hout heeft periodiek onderhoud nodig."}]'::json,
  faq = '[{"question": "Welk materiaal gevelbekleding is het best?", "answer": "Dat hangt af van uw wensen en budget. Kunststof is onderhoudsvrij en voordelig, hout geeft een natuurlijke uitstraling, composiet combineert beide voordelen."}, {"question": "Kan gevelbekleding worden gecombineerd met isolatie?", "answer": "Ja, dat is zelfs zeer aan te raden. Door isolatie toe te voegen verbetert u de energieprestatie van uw woning aanzienlijk."}, {"question": "Hoe lang gaat gevelbekleding mee?", "answer": "Kunststof en composiet gevelbekleding gaan 30-40 jaar mee, houten bekleding 20-30 jaar afhankelijk van onderhoud en houtsoort."}, {"question": "Wat kost gevelbekleding per m²?", "answer": "De kosten variëren tussen €25 en €75 per m² afhankelijk van materiaal en uitvoering. Inclusief isolatie en montage kunt u rekenen op €50-€120 per m²."}]'::json
WHERE slug = 'gevelbekleding';

-- Create HR beglazing product if it doesn't exist yet
INSERT INTO public.products (
  name,
  slug,
  description,
  seo_title,
  seo_description,
  seo_canonical_url,
  hero_badge,
  hero_title,
  hero_description,
  introduction_title,
  introduction_content,
  what_are_title,
  what_are_content,
  benefits_title,
  benefits_description,
  benefits_main_content,
  options_title,
  options_description,
  options_categories,
  services_items,
  information_tabs,
  faq,
  is_active,
  template_type
) 
SELECT 
  'HR++(+) beglazing',
  'hr-beglazing',
  'Hoogrendement beglazing voor optimale isolatie, comfort en energiebesparing in uw woning.',
  'HR++ en HR+++ Beglazing | Energiebesparend | Duurzaam Wonen Nederland',
  'HR++ en HR+++ beglazing voor maximale energiebesparing. ✓ Tot 50% minder warmteverlies ✓ Beter wooncomfort ✓ Condensvrij ✓ Geluidsreductie ✓ 15 jaar garantie.',
  'https://duurzaamwonen.info/hr-beglazing',
  'Beglazing Specialist',
  'HR++ en HR+++ beglazing',
  'Bespaar energie en verhoog het wooncomfort met hoogrendement beglazing voor uw kozijnen.',
  'Waarom kiezen voor HR beglazing?',
  '["HR beglazing (hoogrendement beglazing) is een investering die zich snel terugbetaalt door lagere energiekosten en hoger wooncomfort. Het voorkomt condensatie, reduceert geluid en houdt warmte veel beter binnen.", "Of u nu kiest voor HR++ dubbel glas of HR+++ triple glas, beide varianten bieden aanzienlijke voordelen ten opzichte van gewoon glas en oude beglazing."]'::json,
  'Wat is HR beglazing?',
  '["HR beglazing is hoogrendement isolatieglas waarbij de spouw tussen de glasplaten is gevuld met een edelgas (meestal argon) en voorzien van een speciale coating die warmtestraling tegenhoudt.", "HR++ bestaat uit twee glasplaten, HR+++ uit drie glasplaten. Beide hebben veel betere isolatiewaarden dan gewoon glas, waarbij HR+++ de beste prestaties levert."]'::json,
  'Voordelen van HR beglazing',
  'Ontdek hoe HR beglazing uw wooncomfort en portemonnee ten goede komt.',
  '["Aanzienlijke energiebesparing: HR++ bespaart tot 30% energie, HR+++ zelfs tot 50% vergeleken met gewoon glas.", "Hoger wooncomfort: Geen koude straling van ramen, warmere raampartijen en een gelijkmatigere temperatuur in huis.", "Condensatie preventie: Door warmere glasoppervlakken ontstaat er geen of nauwelijks condensatie op de ramen.", "Geluidsreductie: HR beglazing reduceert buitengeluid aanzienlijk voor een rustiger woonklimaat.", "Hogere woningwaarde: Energiezuinige beglazing verhoogt de waarde en het energielabel van uw woning."]'::json,
  'HR beglazing types',
  'Verschillende HR beglazing opties voor optimale prestaties.',
  '[{"title": "HR++ dubbel glas", "items": ["U-waarde 1.1 W/m²K", "Argon gasvulling", "Low-E coating", "Standaard keuze"]}, {"title": "HR+++ triple glas", "items": ["U-waarde 0.6 W/m²K", "Maximale isolatie", "Drie glasplaten", "Topkwaliteit prestaties"]}, {"title": "HR beglazing plus", "items": ["Extra opties mogelijk", "Zonwering glas", "Geluidswerende uitvoering", "Veiligheidsglas opties"]}, {"title": "Speciale toepassingen", "items": ["Grote glaspartijen", "Gebogen glas", "Gekleurd glas", "Decoratieve uitvoeringen"]}]'::json,
  '[{"title": "HR glas vervanging", "description": "Vervanging van oude beglazing door nieuwe HR beglazing", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Behoud bestaande kozijnen", "Snelle montage", "Directe besparing", "Minimale overlast"], "linkText": "Meer over glasvervanging", "linkUrl": "/hr-beglazing/vervanging"}, {"title": "Complete kozijn vernieuwing", "description": "Nieuwe kozijnen inclusief HR beglazing voor optimaal resultaat", "image": "/lovable-uploads/f45432a2-b79e-4472-b5b9-daaf325d7017.png", "features": ["Nieuwe kozijnen", "HR++ of HR+++ glas", "Perfecte pasvorm", "Maximale prestaties"], "linkText": "Meer over kozijn vernieuwing", "linkUrl": "/hr-beglazing/kozijnen"}]'::json,
  '[{"title": "Technische specificaties", "content": "HR++ heeft een U-waarde van 1.1 W/m²K, HR+++ van 0.6 W/m²K. Ter vergelijking: gewoon dubbel glas heeft een U-waarde van ongeveer 2.8 W/m²K."}, {"title": "Energiebesparing", "content": "HR++ bespaart 30-40% energie vergeleken met gewoon glas, HR+++ bespaart 45-55%. Dit betekent voor een gemiddelde woning €300-500 besparing per jaar."}, {"title": "Installatie", "content": "HR beglazing kan vaak in bestaande kozijnen worden geplaatst. Bij nieuwe kozijnen wordt het glas perfect afgestemd op het profielsysteem voor optimale prestaties."}, {"title": "Certificering", "content": "Al onze HR beglazing is gecertificeerd en voldoet aan de nieuwste Bouwbesluit eisen. We werken alleen met A-merk glasfabrikanten."}]'::json,
  '[{"question": "Wat is het verschil tussen HR++ en HR+++?", "answer": "HR++ is dubbel glas met één Low-E coating, HR+++ is triple glas met twee coatings. HR+++ isoleert beter maar is wel duurder."}, {"question": "Kan HR beglazing in mijn bestaande kozijnen?", "answer": "Vaak wel, mits de kozijnen in goede staat zijn en diep genoeg voor het dikkere glas. Wij beoordelen dit graag voor u."}, {"question": "Hoeveel bespaar ik met HR beglazing?", "answer": "Gemiddeld €300-500 per jaar voor een rijtjeswoning, afhankelijk van het huidige glas en de grootte van de ramen."}, {"question": "Hoe lang gaat HR beglazing mee?", "answer": "HR beglazing heeft een levensduur van 20-25 jaar. De isolatieprestaties blijven gedurende deze periode goed."}]'::json,
  true,
  'service_page'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'hr-beglazing');
